name: N1-OpenWrt-CI S

on:
#  push:
#    branches: 
#      - master
  schedule:
    - cron: 0 20 */3 * *
  watch:
    types: started
  issues:
    types: closed

env:
 SSH_ACTIONS: false
 TZ: Asia/Shanghai

jobs:
  build_openwrt:
    name: Build OpenWrt N1 S
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          
          df -h

      - name: Clone Lean's openwrt
        run: |
          git clone https://github.com/coolsnowwolf/openwrt.git lede
          git clone https://github.com/tuanqing/mknop.git n1

      - name: Git Third Party Plugin
        run: |
          cd lede/package
          git clone https://github.com/fw876/helloworld.git

      - name: Update feeds
        run: |
          cd lede
          git clone https://github.com/tuanqing/install-program package/install-program
          
          sed -i 's/@LINUX_5_4/@!LINUX_4_9/g' ./package/lean/luci-app-flowoffload/Makefile
          sed -i 's/PKG_RELEASE:=19/PKG_RELEASE:=15/g' ./package/lean/luci-app-flowoffload/Makefile
          sed -i '5s/src-git/#src-git/g' ./feeds.conf.default
          
          sed -i 's/\"#src-git\"/\"src-git\"/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: SSH connection to Actions
        uses: P3TERX/debugger-action@main
        if: env.SSH_ACTIONS == 'true'

      - name: Generate Configuration_N1
        env:
          CONFIG_FILE: 'n1_stable.config'
        run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE lede/.config
          sed -i 's/^[ \t]*//g' lede/.config
          
          chmod +x ./n1_diy.sh && ./n1_diy.sh
          
          cd lede && cat .config
          make defconfig

      - name: Make download
        run: |
          cd lede
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          cd lede
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Build firmware
        run: |
          cd n1
          cp ../lede/bin/targets/*/*/*.tar.gz ./openwrt
          sudo ./make -d
          
          i=0
          cd out
          for x in $(ls .); do
            cd $x
            filename=$(ls .)
            filename=${filename%.*}
            gzip *.img
            cd ../
            echo "::set-env name=firmware_$((++i))::$filename"
          done

      - name: Upload firmware @ kernel 5.4.60
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.firmware_1 }}
          path: ./n1/out/5.4.60

      - name: Upload Packages
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_N1_Packages
          path: ./lede/bin/packages/
